# Generated by Django 4.2.23 on 2025-06-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='nickname',
        ),
    ]
