# Generated by Django 4.2.23 on 2025-06-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nickname',
            field=models.TextField(blank=True, default=''),
        ),
    ]
